### ISSUE TITLE
When I put a "%" in my character's name this happens

### ISSUE THREAD

**Issue by vicusdanielson** [qndel/TchernobogBugTracker#16]
I named my char "70%full-t.stash and it automatically converted to this after creating.

[https://postimg.cc/zyxjf1dX](url)

**Comment by qndel** [comment]
Thx for the report, but for the future, paste pics directly into github

**Comment by qndel** [comment]
That's because 70%f affects printing characters and makes the game treat 70 as a floating number.
I'm not going to fix that. If you want to ruin your character, up to you :)
