### ISSUE TITLE
Trang Oul set also has slower attack time

### ISSUE THREAD

**Issue by vicusdanielson** [qndel/TchernobogBugTracker#17]
This case is like how it was with Aldur.

![withnohelm](https://user-images.githubusercontent.com/20937410/57334389-ddc34e80-711f-11e9-9ee9-e7c7136c3f66.jpg)
This is with no helm.
![withhelm](https://user-images.githubusercontent.com/20937410/57334394-e3209900-711f-11e9-9b4a-f5e6ab9e8dd6.jpg)
This is with helm.

**Comment by qndel** [comment]
it's like this with ALL transformations, I know about it
