### ISSUE TITLE
Music volume setting is ignored when you start a new game and/or restart Tcherno

### ISSUE THREAD

**Issue by Psojed** [qndel/TchernobogBugTracker#3]
Title.

Reproduce:
1) Go ingame, ESC->Sound Options->Music slider, set all the way to the left (music is off).
2a) ESC - New game
3a) When you start a New game, music is playing until you move the slider again or press M twice.
OR
2b) ESC - Exit game.
3b) When you launch the game again, music in the menu is playing.

**Comment by qndel** [comment]
That's because sound settings are saved in the player. No player is loaded while you are in the main menu = no settings

**Comment by qndel** [comment]
Fixed in 0.2.0
