### ISSUE TITLE
Charged Bolt sparks activate block animation, but you take full damage

### ISSUE THREAD

**Issue by Psojed** [qndel/TchernobogBugTracker#4]
Tested on Magistrates with Warrior.

Steps to reproduce:
1) Find a Magistrate monster variety in Hell levels.
2) Equip a shield with high block chance %.
3) Get hit by the sparks.

I haven't tested if block happens with a Lightning enchanted boss or with Charged Bolt in PvP.

**Comment by qndel** [comment]
how does block work with spells in general? Can you block spells? What does it do? How is charged bolt different from other spells?

**Comment by Psojed** [comment]
Jarulf's guide to original Diablo states that: http://www.bigd-online.com/JG/Body/JG2-2.html#2.2.1

> When you are hit by a melee weapon, an arrow, or magic (while not having any resistance), you will try to block the attack (in Hellfire you will try to block even if you have resistance).

This is elabored in the Spells section: http://www.bigd-online.com/JG/Body/JG4-1.html#4.1.2

> Blockable: This will tell if a spell is blockable or not. In Diablo, you will only block if you have 0% resistance.

Next, section 4.1.3 details blockable spells: http://www.bigd-online.com/JG/Body/JG4-1.html#4.1.3
Charged Bolt **is** a blockable spell.
Finally, section 6.1 details what happens when you block: http://www.bigd-online.com/JG/Body/JG6-1.html

> C. Blocking | When a player is hit, the game will check if he or she managed to block the attack or not. If a block was done, the Damage step is generally skipped.

From observation, in Tcherno you can block spells even if your resistance to its element is not zero.
When you block an attack or direct spell like arrow/firebolt shot by a trap in the cathedral, you take no damage. Therefore you should also take no damage when blocking a Charged Bolt.

**Comment by qndel** [comment]
Jarulf's guide is useless in tchernobog : P I expected answers backed up by tests in tchernobog :D

**Comment by Psojed** [comment]
Read the final paragraph then ;)

PS: I didn't answer how is charged bolt different. I don't know, it shouldn't be different :wink:

**Comment by qndel** [comment]
resolved in 0.1.4b (turned out blocking everything except melee was bugged)
