### ISSUE TITLE
Result of upgrading long sword / claymore are in correct

### ISSUE THREAD

**Issue by MisoPaste** [qndel/TchernobogBugTracker#5]
ive tested uptier long sword with upgrade magic/rare/unique/set recipe, result was espadon base (2nd tier of claymore)
then, claymore goes to battle sword (2nd tier of long sword)

generally, long sword upgrade should be into battle sword.
claymore should be into espadon.

*that issue has already reported by Danielson released 0.1.1

**Comment by qndel** [comment]
fixed in 0.1.4b
