### ISSUE TITLE
Debuff from cold enchanted rare bosses persist death

### ISSUE THREAD

**Issue by szakalakakaka** [qndel/TchernobogBugTracker#8]
Like in topic, Boss dies, he cast ice nova(?) which gives debuff on my char, it also kills my char, but debuff persist death

**Comment by qndel** [comment]
Usually I'd say it's not worth my time and it's good enough as it is but I think it might be connected to dying 50 times in town when you die from insanity so I'll probably look at it : )

**Comment by qndel** [comment]
#Tchernobog 0.1.5b
- Unfreeze on death
- Insanity gets removed on death
- Unfreeze on changing levels
- Improving crash logs

Fixed in 0.1.5b
